
dist: trusty
language: node_js
node_js: stable

jobs:
  include:
    - stage: tests
      script:
        - yarn test:ci
    - stage: storybook release
      if: branch = master
      script:
        - yarn build-storybook
        - yarn deploy-storybook -- --ci
    - stage: npm release
      if: branch = master
      before_deploy:
      - yarn build:lib
      deploy:
        skip_cleanup: true
        provider: npm
        email: "webdev@experium.ru"
        api_key: "$NPM_API_KEY"
        on:
          branch: master
